version: "2.1"

services:
    sql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=12345pass --execute \"SHOW DATABASES\""
            interval: 5s
            timeout: 30s
            retries: 5
        environment:
            MYSQL_ROOT_PASSWORD: 12345pass
            MYSQL_DATABASE: licensoft

    licensoft:
        build: 
            context: ./
            args: 
                privateStripeKey: sk_test_HXX6s2mN8JqMUytYfvkwB0dr00CfDzVlYA
        image: kikeajani/licensoft:latest
        links:
            - sql
        depends_on:
            sql:
               condition: service_healthy
        ports:
            - "8080:8080"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://sql/licensoft?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 12345pass
            
    
    
    frontend:
        build: 
            context: ../frontend
            args: 
                publicStripeKey: pk_test_mAWlLKZrpvwEye9QZzRZzsSG00M6tsJ3QS
        #image: kikeajani/frontend-licensoft:latest
        #environment:
         #       publicStripeKeyEnv: environmentKey
          #      ENVIRONMENT: compose
           #     test: composetest
        depends_on:
            - licensoft
        ports:
            - "80:80"
        
        

