version: "2.1"

services:
    sql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=12345pass --execute \"SHOW DATABASES\""
            interval: 5s
            timeout: 30s
            retries: 5
        environment:
            MYSQL_ROOT_PASSWORD: 12345pass
            MYSQL_DATABASE: licensoft

    licensoft:
        image: kikeajani/licensoft:latest
        links:
            - sql
        depends_on:
            sql:
               condition: service_healthy
        ports:
            - "8080:8080"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://sql/licensoft?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 12345pass
            STRIPE_PRIVATEKEY: sk_test_HXX6s2mN8JqMUytYfvkwB0dr00CfDzVlYA
            STRIPE_PUBLICKEY: pk_test_mAWlLKZrpvwEye9QZzRZzsSG00M6tsJ3QS